# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_document.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blens_overlay_document.proto\x12\x04lens\"0\n\x13LensOverlayDocument\x12\x19\n\x05pages\x18\x01 \x03(\x0b\x32\n.lens.Page\"2\n\x04Page\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x15\n\rtext_segments\x18\x04 \x03(\tB\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LENSOVERLAYDOCUMENT']._serialized_start=37
  _globals['_LENSOVERLAYDOCUMENT']._serialized_end=85
  _globals['_PAGE']._serialized_start=87
  _globals['_PAGE']._serialized_end=137
# @@protoc_insertion_point(module_scope)
