# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_visual_input_type.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_visual_input_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$lens_overlay_visual_input_type.proto\x12\x04lens*\x87\x01\n\x1aLensOverlayVisualInputType\x12\x1d\n\x19VISUAL_INPUT_TYPE_UNKNOWN\x10\x00\x12\x19\n\x15VISUAL_INPUT_TYPE_PDF\x10\x04\x12\x1d\n\x19VISUAL_INPUT_TYPE_WEBPAGE\x10\x05\"\x04\x08\x01\x10\x01\"\x04\x08\x02\x10\x02\"\x04\x08\x03\x10\x03\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_visual_input_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LENSOVERLAYVISUALINPUTTYPE']._serialized_start=47
  _globals['_LENSOVERLAYVISUALINPUTTYPE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
