# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_filters.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_filters.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alens_overlay_filters.proto\x12\x04lens\"\xc6\x01\n\rAppliedFilter\x12\x30\n\x0b\x66ilter_type\x18\x01 \x01(\x0e\x32\x1b.lens.LensOverlayFilterType\x12\x32\n\ttranslate\x18\x03 \x01(\x0b\x32\x1d.lens.AppliedFilter.TranslateH\x00\x1a=\n\tTranslate\x12\x17\n\x0ftarget_language\x18\x01 \x01(\t\x12\x17\n\x0fsource_language\x18\x02 \x01(\tB\x10\n\x0e\x66ilter_payload\"5\n\x0e\x41ppliedFilters\x12#\n\x06\x66ilter\x18\x01 \x03(\x0b\x32\x13.lens.AppliedFilter*P\n\x15LensOverlayFilterType\x12\x17\n\x13UNKNOWN_FILTER_TYPE\x10\x00\x12\r\n\tTRANSLATE\x10\x02\x12\x0f\n\x0b\x41UTO_FILTER\x10\x07\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_filters_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LENSOVERLAYFILTERTYPE']._serialized_start=292
  _globals['_LENSOVERLAYFILTERTYPE']._serialized_end=372
  _globals['_APPLIEDFILTER']._serialized_start=37
  _globals['_APPLIEDFILTER']._serialized_end=235
  _globals['_APPLIEDFILTER_TRANSLATE']._serialized_start=156
  _globals['_APPLIEDFILTER_TRANSLATE']._serialized_end=217
  _globals['_APPLIEDFILTERS']._serialized_start=237
  _globals['_APPLIEDFILTERS']._serialized_end=290
# @@protoc_insertion_point(module_scope)
