# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_contextual_inputs.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_contextual_inputs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import lens_overlay_request_id_pb2 as lens__overlay__request__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$lens_overlay_contextual_inputs.proto\x12\x04lens\x1a\x1dlens_overlay_request_id.proto\"\xb9\x01\n\x1bLensOverlayContextualInputs\x12L\n\x06inputs\x18\x01 \x03(\x0b\x32<.lens.LensOverlayContextualInputs.LensOverlayContextualInput\x1aL\n\x1aLensOverlayContextualInput\x12.\n\nrequest_id\x18\x01 \x01(\x0b\x32\x1a.lens.LensOverlayRequestIdB\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_contextual_inputs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LENSOVERLAYCONTEXTUALINPUTS']._serialized_start=78
  _globals['_LENSOVERLAYCONTEXTUALINPUTS']._serialized_end=263
  _globals['_LENSOVERLAYCONTEXTUALINPUTS_LENSOVERLAYCONTEXTUALINPUT']._serialized_start=187
  _globals['_LENSOVERLAYCONTEXTUALINPUTS_LENSOVERLAYCONTEXTUALINPUT']._serialized_end=263
# @@protoc_insertion_point(module_scope)
