# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_image_crop.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_image_crop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2
from . import lens_overlay_payload_pb2 as lens__overlay__payload__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlens_overlay_image_crop.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\x1a\x1alens_overlay_payload.proto\"k\n\tImageCrop\x12\x0f\n\x07\x63rop_id\x18\x01 \x01(\t\x12 \n\x05image\x18\x02 \x01(\x0b\x32\x11.lens.ClientImage\x12%\n\x0bzoomed_crop\x18\x03 \x01(\x0b\x32\x10.lens.ZoomedCropJ\x04\x08\x04\x10\x05\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_image_crop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_IMAGECROP']._serialized_start=96
  _globals['_IMAGECROP']._serialized_end=203
# @@protoc_insertion_point(module_scope)
