# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_stickiness_signals.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_stickiness_signals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import lens_overlay_math_solver_query_pb2 as lens__overlay__math__solver__query__pb2
from . import lens_overlay_message_set_pb2 as lens__overlay__message__set__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%lens_overlay_stickiness_signals.proto\x12\x04lens\x1a$lens_overlay_math_solver_query.proto\x1a\x1elens_overlay_message_set.proto\"\xfb\x01\n\x11StickinessSignals\x12\x37\n\x0cid_namespace\x18\x01 \x01(\x0e\x32!.lens.StickinessSignals.Namespace\x12(\n\x0einterpretation\x18\x1c \x01(\x0b\x32\x10.lens.MessageSet\x12@\n\x19\x65\x64ucation_input_extension\x18y \x01(\x0b\x32\x1d.lens.EducationInputExtension\"A\n\tNamespace\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0eTRANSLATE_LITE\x10\x38\x12\x13\n\x0f\x45\x44UCATION_INPUT\x10O\"K\n\x17\x45\x64ucationInputExtension\x12\x30\n\x11math_solver_query\x18\x01 \x01(\x0b\x32\x15.lens.MathSolverQueryB\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_stickiness_signals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_STICKINESSSIGNALS']._serialized_start=118
  _globals['_STICKINESSSIGNALS']._serialized_end=369
  _globals['_STICKINESSSIGNALS_NAMESPACE']._serialized_start=304
  _globals['_STICKINESSSIGNALS_NAMESPACE']._serialized_end=369
  _globals['_EDUCATIONINPUTEXTENSION']._serialized_start=371
  _globals['_EDUCATIONINPUTEXTENSION']._serialized_end=446
# @@protoc_insertion_point(module_scope)
