# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aim_communication.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'aim_communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aim_query_pb2 as aim__query__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61im_communication.proto\x12\x04lens\x1a\x0f\x61im_query.proto\">\n\rHandshakePing\x12-\n\x0c\x63\x61pabilities\x18\x01 \x03(\x0e\x32\x17.lens.FeatureCapability\"2\n\x0bSubmitQuery\x12#\n\x07payload\x18\x01 \x01(\x0b\x32\x12.lens.QueryPayload\"B\n\x11HandshakeResponse\x12-\n\x0c\x63\x61pabilities\x18\x01 \x03(\x0e\x32\x17.lens.FeatureCapability\"\x7f\n\x12\x43lientToAimMessage\x12-\n\x0ehandshake_ping\x18\x01 \x01(\x0b\x32\x13.lens.HandshakePingH\x00\x12)\n\x0csubmit_query\x18\x02 \x01(\x0b\x32\x11.lens.SubmitQueryH\x00\x42\x0f\n\revent_message\"\\\n\x12\x41imToClientMessage\x12\x35\n\x12handshake_response\x18\x01 \x01(\x0b\x32\x17.lens.HandshakeResponseH\x00\x42\x0f\n\revent_message* \n\x11\x46\x65\x61tureCapability\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aim_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_FEATURECAPABILITY']._serialized_start=457
  _globals['_FEATURECAPABILITY']._serialized_end=489
  _globals['_HANDSHAKEPING']._serialized_start=50
  _globals['_HANDSHAKEPING']._serialized_end=112
  _globals['_SUBMITQUERY']._serialized_start=114
  _globals['_SUBMITQUERY']._serialized_end=164
  _globals['_HANDSHAKERESPONSE']._serialized_start=166
  _globals['_HANDSHAKERESPONSE']._serialized_end=232
  _globals['_CLIENTTOAIMMESSAGE']._serialized_start=234
  _globals['_CLIENTTOAIMMESSAGE']._serialized_end=361
  _globals['_AIMTOCLIENTMESSAGE']._serialized_start=363
  _globals['_AIMTOCLIENTMESSAGE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
