# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_interaction_request_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2
import owocr.py_lens.lens_overlay_text_query_pb2 as lens__overlay__text__query__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/lens_overlay_interaction_request_metadata.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\x1a\x1dlens_overlay_text_query.proto\"\xb9\x07\n%LensOverlayInteractionRequestMetadata\x12>\n\x04type\x18\x01 \x01(\x0e\x32\x30.lens.LensOverlayInteractionRequestMetadata.Type\x12Y\n\x12selection_metadata\x18\x02 \x01(\x0b\x32=.lens.LensOverlayInteractionRequestMetadata.SelectionMetadata\x12Q\n\x0equery_metadata\x18\x04 \x01(\x0b\x32\x39.lens.LensOverlayInteractionRequestMetadata.QueryMetadata\x1a\xb6\x03\n\x11SelectionMetadata\x12T\n\x05point\x18\x01 \x01(\x0b\x32\x43.lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.PointH\x00\x12V\n\x06region\x18\x02 \x01(\x0b\x32\x44.lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.RegionH\x00\x12V\n\x06object\x18\x03 \x01(\x0b\x32\x44.lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.ObjectH\x00\x1a\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x1a\x30\n\x06Region\x12&\n\x06region\x18\x01 \x01(\x0b\x32\x16.lens.CenterRotatedBox\x1a=\n\x06Object\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12 \n\x08geometry\x18\x02 \x01(\x0b\x32\x0e.lens.GeometryB\x0b\n\tselection\x1a:\n\rQueryMetadata\x12#\n\ntext_query\x18\x02 \x01(\x0b\x32\x0f.lens.TextQueryJ\x04\x08\x01\x10\x02\"\xa6\x01\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03TAP\x10\x01\x12\n\n\x06REGION\x10\x02\x12\x12\n\x0eTEXT_SELECTION\x10\x03\x12\x11\n\rREGION_SEARCH\x10\x04\x12\x16\n\x12OBJECT_FULFILLMENT\x10\x05\x12\x1b\n\x17\x43ONTEXTUAL_SEARCH_QUERY\x10\t\x12\r\n\tPDF_QUERY\x10\n\x12\x11\n\rWEBPAGE_QUERY\x10\x0bJ\x04\x08\x03\x10\x04\x42\x02H\x03\x62\x06proto3')



_LENSOVERLAYINTERACTIONREQUESTMETADATA = DESCRIPTOR.message_types_by_name['LensOverlayInteractionRequestMetadata']
_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA = _LENSOVERLAYINTERACTIONREQUESTMETADATA.nested_types_by_name['SelectionMetadata']
_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_POINT = _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA.nested_types_by_name['Point']
_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_REGION = _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA.nested_types_by_name['Region']
_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_OBJECT = _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA.nested_types_by_name['Object']
_LENSOVERLAYINTERACTIONREQUESTMETADATA_QUERYMETADATA = _LENSOVERLAYINTERACTIONREQUESTMETADATA.nested_types_by_name['QueryMetadata']
_LENSOVERLAYINTERACTIONREQUESTMETADATA_TYPE = _LENSOVERLAYINTERACTIONREQUESTMETADATA.enum_types_by_name['Type']
LensOverlayInteractionRequestMetadata = _reflection.GeneratedProtocolMessageType('LensOverlayInteractionRequestMetadata', (_message.Message,), {

  'SelectionMetadata' : _reflection.GeneratedProtocolMessageType('SelectionMetadata', (_message.Message,), {

    'Point' : _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
      'DESCRIPTOR' : _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_POINT,
      '__module__' : 'lens_overlay_interaction_request_metadata_pb2'
      # @@protoc_insertion_point(class_scope:lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.Point)
      })
    ,

    'Region' : _reflection.GeneratedProtocolMessageType('Region', (_message.Message,), {
      'DESCRIPTOR' : _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_REGION,
      '__module__' : 'lens_overlay_interaction_request_metadata_pb2'
      # @@protoc_insertion_point(class_scope:lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.Region)
      })
    ,

    'Object' : _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
      'DESCRIPTOR' : _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_OBJECT,
      '__module__' : 'lens_overlay_interaction_request_metadata_pb2'
      # @@protoc_insertion_point(class_scope:lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.Object)
      })
    ,
    'DESCRIPTOR' : _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA,
    '__module__' : 'lens_overlay_interaction_request_metadata_pb2'
    # @@protoc_insertion_point(class_scope:lens.LensOverlayInteractionRequestMetadata.SelectionMetadata)
    })
  ,

  'QueryMetadata' : _reflection.GeneratedProtocolMessageType('QueryMetadata', (_message.Message,), {
    'DESCRIPTOR' : _LENSOVERLAYINTERACTIONREQUESTMETADATA_QUERYMETADATA,
    '__module__' : 'lens_overlay_interaction_request_metadata_pb2'
    # @@protoc_insertion_point(class_scope:lens.LensOverlayInteractionRequestMetadata.QueryMetadata)
    })
  ,
  'DESCRIPTOR' : _LENSOVERLAYINTERACTIONREQUESTMETADATA,
  '__module__' : 'lens_overlay_interaction_request_metadata_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayInteractionRequestMetadata)
  })
_sym_db.RegisterMessage(LensOverlayInteractionRequestMetadata)
_sym_db.RegisterMessage(LensOverlayInteractionRequestMetadata.SelectionMetadata)
_sym_db.RegisterMessage(LensOverlayInteractionRequestMetadata.SelectionMetadata.Point)
_sym_db.RegisterMessage(LensOverlayInteractionRequestMetadata.SelectionMetadata.Region)
_sym_db.RegisterMessage(LensOverlayInteractionRequestMetadata.SelectionMetadata.Object)
_sym_db.RegisterMessage(LensOverlayInteractionRequestMetadata.QueryMetadata)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYINTERACTIONREQUESTMETADATA._serialized_start=118
  _LENSOVERLAYINTERACTIONREQUESTMETADATA._serialized_end=1071
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA._serialized_start=398
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA._serialized_end=836
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_POINT._serialized_start=681
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_POINT._serialized_end=710
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_REGION._serialized_start=712
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_REGION._serialized_end=760
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_OBJECT._serialized_start=762
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_OBJECT._serialized_end=823
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_QUERYMETADATA._serialized_start=838
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_QUERYMETADATA._serialized_end=896
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_TYPE._serialized_start=899
  _LENSOVERLAYINTERACTIONREQUESTMETADATA_TYPE._serialized_end=1065
# @@protoc_insertion_point(module_scope)
