# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_math_solver_query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$lens_overlay_math_solver_query.proto\x12\x04lens\".\n\x0fMathSolverQuery\x12\x1b\n\x13math_input_equation\x18\x03 \x01(\tB\x02H\x03\x62\x06proto3')



_MATHSOLVERQUERY = DESCRIPTOR.message_types_by_name['MathSolverQuery']
MathSolverQuery = _reflection.GeneratedProtocolMessageType('MathSolverQuery', (_message.Message,), {
  'DESCRIPTOR' : _MATHSOLVERQUERY,
  '__module__' : 'lens_overlay_math_solver_query_pb2'
  # @@protoc_insertion_point(class_scope:lens.MathSolverQuery)
  })
_sym_db.RegisterMessage(MathSolverQuery)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _MATHSOLVERQUERY._serialized_start=46
  _MATHSOLVERQUERY._serialized_end=92
# @@protoc_insertion_point(module_scope)
