# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_document.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blens_overlay_document.proto\x12\x04lens\"0\n\x13LensOverlayDocument\x12\x19\n\x05pages\x18\x01 \x03(\x0b\x32\n.lens.Page\"2\n\x04Page\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x15\n\rtext_segments\x18\x04 \x03(\tB\x02H\x03\x62\x06proto3')



_LENSOVERLAYDOCUMENT = DESCRIPTOR.message_types_by_name['LensOverlayDocument']
_PAGE = DESCRIPTOR.message_types_by_name['Page']
LensOverlayDocument = _reflection.GeneratedProtocolMessageType('LensOverlayDocument', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYDOCUMENT,
  '__module__' : 'lens_overlay_document_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayDocument)
  })
_sym_db.RegisterMessage(LensOverlayDocument)

Page = _reflection.GeneratedProtocolMessageType('Page', (_message.Message,), {
  'DESCRIPTOR' : _PAGE,
  '__module__' : 'lens_overlay_document_pb2'
  # @@protoc_insertion_point(class_scope:lens.Page)
  })
_sym_db.RegisterMessage(Page)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYDOCUMENT._serialized_start=37
  _LENSOVERLAYDOCUMENT._serialized_end=85
  _PAGE._serialized_start=87
  _PAGE._serialized_end=137
# @@protoc_insertion_point(module_scope)
