# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_image_crop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2
import owocr.py_lens.lens_overlay_payload_pb2 as lens__overlay__payload__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlens_overlay_image_crop.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\x1a\x1alens_overlay_payload.proto\"k\n\tImageCrop\x12\x0f\n\x07\x63rop_id\x18\x01 \x01(\t\x12 \n\x05image\x18\x02 \x01(\x0b\x32\x11.lens.ClientImage\x12%\n\x0bzoomed_crop\x18\x03 \x01(\x0b\x32\x10.lens.ZoomedCropJ\x04\x08\x04\x10\x05\x42\x02H\x03\x62\x06proto3')



_IMAGECROP = DESCRIPTOR.message_types_by_name['ImageCrop']
ImageCrop = _reflection.GeneratedProtocolMessageType('ImageCrop', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECROP,
  '__module__' : 'lens_overlay_image_crop_pb2'
  # @@protoc_insertion_point(class_scope:lens.ImageCrop)
  })
_sym_db.RegisterMessage(ImageCrop)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _IMAGECROP._serialized_start=96
  _IMAGECROP._serialized_end=203
# @@protoc_insertion_point(module_scope)
