# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_video_context_input_params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-lens_overlay_video_context_input_params.proto\x12\x04lens\"1\n\"LensOverlayVideoContextInputParams\x12\x0b\n\x03url\x18\x01 \x01(\tB\x02H\x03\x62\x06proto3')



_LENSOVERLAYVIDEOCONTEXTINPUTPARAMS = DESCRIPTOR.message_types_by_name['LensOverlayVideoContextInputParams']
LensOverlayVideoContextInputParams = _reflection.GeneratedProtocolMessageType('LensOverlayVideoContextInputParams', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYVIDEOCONTEXTINPUTPARAMS,
  '__module__' : 'lens_overlay_video_context_input_params_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayVideoContextInputParams)
  })
_sym_db.RegisterMessage(LensOverlayVideoContextInputParams)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYVIDEOCONTEXTINPUTPARAMS._serialized_start=55
  _LENSOVERLAYVIDEOCONTEXTINPUTPARAMS._serialized_end=104
# @@protoc_insertion_point(module_scope)
