# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_overlay_object.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_overlay_object.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!lens_overlay_overlay_object.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\"\xac\x03\n\rOverlayObject\x12\n\n\x02id\x18\x01 \x01(\t\x12 \n\x08geometry\x18\x02 \x01(\x0b\x32\x0e.lens.Geometry\x12\x41\n\x12rendering_metadata\x18\x08 \x01(\x0b\x32%.lens.OverlayObject.RenderingMetadata\x12I\n\x16interaction_properties\x18\x04 \x01(\x0b\x32).lens.OverlayObject.InteractionProperties\x12\x14\n\x0cis_fulfilled\x18\t \x01(\x08\x1a\x80\x01\n\x11RenderingMetadata\x12\x45\n\x0brender_type\x18\x01 \x01(\x0e\x32\x30.lens.OverlayObject.RenderingMetadata.RenderType\"$\n\nRenderType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05GLEAM\x10\x01\x1a.\n\x15InteractionProperties\x12\x15\n\rselect_on_tap\x18\x01 \x01(\x08J\x04\x08\x03\x10\x04J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_overlay_object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_OVERLAYOBJECT']._serialized_start=73
  _globals['_OVERLAYOBJECT']._serialized_end=501
  _globals['_OVERLAYOBJECT_RENDERINGMETADATA']._serialized_start=301
  _globals['_OVERLAYOBJECT_RENDERINGMETADATA']._serialized_end=429
  _globals['_OVERLAYOBJECT_RENDERINGMETADATA_RENDERTYPE']._serialized_start=393
  _globals['_OVERLAYOBJECT_RENDERINGMETADATA_RENDERTYPE']._serialized_end=429
  _globals['_OVERLAYOBJECT_INTERACTIONPROPERTIES']._serialized_start=431
  _globals['_OVERLAYOBJECT_INTERACTIONPROPERTIES']._serialized_end=477
# @@protoc_insertion_point(module_scope)
