# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_overlay_object.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!lens_overlay_overlay_object.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\"\xac\x03\n\rOverlayObject\x12\n\n\x02id\x18\x01 \x01(\t\x12 \n\x08geometry\x18\x02 \x01(\x0b\x32\x0e.lens.Geometry\x12\x41\n\x12rendering_metadata\x18\x08 \x01(\x0b\x32%.lens.OverlayObject.RenderingMetadata\x12I\n\x16interaction_properties\x18\x04 \x01(\x0b\x32).lens.OverlayObject.InteractionProperties\x12\x14\n\x0cis_fulfilled\x18\t \x01(\x08\x1a\x80\x01\n\x11RenderingMetadata\x12\x45\n\x0brender_type\x18\x01 \x01(\x0e\x32\x30.lens.OverlayObject.RenderingMetadata.RenderType\"$\n\nRenderType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05GLEAM\x10\x01\x1a.\n\x15InteractionProperties\x12\x15\n\rselect_on_tap\x18\x01 \x01(\x08J\x04\x08\x03\x10\x04J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08\x42\x02H\x03\x62\x06proto3')



_OVERLAYOBJECT = DESCRIPTOR.message_types_by_name['OverlayObject']
_OVERLAYOBJECT_RENDERINGMETADATA = _OVERLAYOBJECT.nested_types_by_name['RenderingMetadata']
_OVERLAYOBJECT_INTERACTIONPROPERTIES = _OVERLAYOBJECT.nested_types_by_name['InteractionProperties']
_OVERLAYOBJECT_RENDERINGMETADATA_RENDERTYPE = _OVERLAYOBJECT_RENDERINGMETADATA.enum_types_by_name['RenderType']
OverlayObject = _reflection.GeneratedProtocolMessageType('OverlayObject', (_message.Message,), {

  'RenderingMetadata' : _reflection.GeneratedProtocolMessageType('RenderingMetadata', (_message.Message,), {
    'DESCRIPTOR' : _OVERLAYOBJECT_RENDERINGMETADATA,
    '__module__' : 'lens_overlay_overlay_object_pb2'
    # @@protoc_insertion_point(class_scope:lens.OverlayObject.RenderingMetadata)
    })
  ,

  'InteractionProperties' : _reflection.GeneratedProtocolMessageType('InteractionProperties', (_message.Message,), {
    'DESCRIPTOR' : _OVERLAYOBJECT_INTERACTIONPROPERTIES,
    '__module__' : 'lens_overlay_overlay_object_pb2'
    # @@protoc_insertion_point(class_scope:lens.OverlayObject.InteractionProperties)
    })
  ,
  'DESCRIPTOR' : _OVERLAYOBJECT,
  '__module__' : 'lens_overlay_overlay_object_pb2'
  # @@protoc_insertion_point(class_scope:lens.OverlayObject)
  })
_sym_db.RegisterMessage(OverlayObject)
_sym_db.RegisterMessage(OverlayObject.RenderingMetadata)
_sym_db.RegisterMessage(OverlayObject.InteractionProperties)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _OVERLAYOBJECT._serialized_start=73
  _OVERLAYOBJECT._serialized_end=501
  _OVERLAYOBJECT_RENDERINGMETADATA._serialized_start=301
  _OVERLAYOBJECT_RENDERINGMETADATA._serialized_end=429
  _OVERLAYOBJECT_RENDERINGMETADATA_RENDERTYPE._serialized_start=393
  _OVERLAYOBJECT_RENDERINGMETADATA_RENDERTYPE._serialized_end=429
  _OVERLAYOBJECT_INTERACTIONPROPERTIES._serialized_start=431
  _OVERLAYOBJECT_INTERACTIONPROPERTIES._serialized_end=477
# @@protoc_insertion_point(module_scope)
