# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_polygon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alens_overlay_polygon.proto\x12\x04lens\"\x8e\x02\n\x07Polygon\x12$\n\x06vertex\x18\x01 \x03(\x0b\x32\x14.lens.Polygon.Vertex\x12\x35\n\x0fvertex_ordering\x18\x02 \x01(\x0e\x32\x1c.lens.Polygon.VertexOrdering\x12-\n\x0f\x63oordinate_type\x18\x03 \x01(\x0e\x32\x14.lens.CoordinateType\x1a\x1e\n\x06Vertex\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"W\n\x0eVertexOrdering\x12\x1f\n\x1bVERTEX_ORDERING_UNSPECIFIED\x10\x00\x12\r\n\tCLOCKWISE\x10\x01\x12\x15\n\x11\x43OUNTER_CLOCKWISE\x10\x02*L\n\x0e\x43oordinateType\x12\x1f\n\x1b\x43OORDINATE_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n\nNORMALIZED\x10\x01\x12\t\n\x05IMAGE\x10\x02\x42\x02H\x03\x62\x06proto3')

_COORDINATETYPE = DESCRIPTOR.enum_types_by_name['CoordinateType']
CoordinateType = enum_type_wrapper.EnumTypeWrapper(_COORDINATETYPE)
COORDINATE_TYPE_UNSPECIFIED = 0
NORMALIZED = 1
IMAGE = 2


_POLYGON = DESCRIPTOR.message_types_by_name['Polygon']
_POLYGON_VERTEX = _POLYGON.nested_types_by_name['Vertex']
_POLYGON_VERTEXORDERING = _POLYGON.enum_types_by_name['VertexOrdering']
Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), {

  'Vertex' : _reflection.GeneratedProtocolMessageType('Vertex', (_message.Message,), {
    'DESCRIPTOR' : _POLYGON_VERTEX,
    '__module__' : 'lens_overlay_polygon_pb2'
    # @@protoc_insertion_point(class_scope:lens.Polygon.Vertex)
    })
  ,
  'DESCRIPTOR' : _POLYGON,
  '__module__' : 'lens_overlay_polygon_pb2'
  # @@protoc_insertion_point(class_scope:lens.Polygon)
  })
_sym_db.RegisterMessage(Polygon)
_sym_db.RegisterMessage(Polygon.Vertex)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _COORDINATETYPE._serialized_start=309
  _COORDINATETYPE._serialized_end=385
  _POLYGON._serialized_start=37
  _POLYGON._serialized_end=307
  _POLYGON_VERTEX._serialized_start=188
  _POLYGON_VERTEX._serialized_end=218
  _POLYGON_VERTEXORDERING._serialized_start=220
  _POLYGON_VERTEXORDERING._serialized_end=307
# @@protoc_insertion_point(module_scope)
