# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_selection_type.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_selection_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!lens_overlay_selection_type.proto\x12\x04lens*\xfd\x02\n\x18LensOverlaySelectionType\x12\x1a\n\x16UNKNOWN_SELECTION_TYPE\x10\x00\x12\x10\n\x0cTAP_ON_EMPTY\x10\x01\x12\x19\n\x15SELECT_TEXT_HIGHLIGHT\x10\x03\x12\x11\n\rREGION_SEARCH\x10\x07\x12\x12\n\x0eINJECTED_IMAGE\x10\n\x12\x17\n\x13TAP_ON_REGION_GLEAM\x10\x0f\x12\x15\n\x11MULTIMODAL_SEARCH\x10\x12\x12\x1a\n\x16SELECT_TRANSLATED_TEXT\x10\x15\x12\x11\n\rTAP_ON_OBJECT\x10\x16\x12 \n\x1cMULTIMODAL_SUGGEST_TYPEAHEAD\x10\x19\x12\"\n\x1eMULTIMODAL_SUGGEST_ZERO_PREFIX\x10\x1a\x12\x1e\n\x1aMULTIMODAL_SELECTION_CLEAR\x10\x1b\x12\x12\n\x0eTRANSLATE_CHIP\x10\x34\x12\x18\n\x14SYMBOLIC_MATH_OBJECT\x10\x35\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_selection_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LENSOVERLAYSELECTIONTYPE']._serialized_start=44
  _globals['_LENSOVERLAYSELECTIONTYPE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
