# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_geometry.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_polygon_pb2 as lens__overlay__polygon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blens_overlay_geometry.proto\x12\x04lens\x1a\x1alens_overlay_polygon.proto\"\x98\x01\n\x10\x43\x65nterRotatedBox\x12\x10\n\x08\x63\x65nter_x\x18\x01 \x01(\x02\x12\x10\n\x08\x63\x65nter_y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x12\n\nrotation_z\x18\x05 \x01(\x02\x12-\n\x0f\x63oordinate_type\x18\x06 \x01(\x0e\x32\x14.lens.CoordinateType\"}\n\x08Geometry\x12,\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\x16.lens.CenterRotatedBox\x12+\n\x14segmentation_polygon\x18\x05 \x03(\x0b\x32\r.lens.PolygonJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x06\x10\x07\"m\n\nZoomedCrop\x12$\n\x04\x63rop\x18\x01 \x01(\x0b\x32\x16.lens.CenterRotatedBox\x12\x14\n\x0cparent_width\x18\x02 \x01(\x05\x12\x15\n\rparent_height\x18\x03 \x01(\x05\x12\x0c\n\x04zoom\x18\x04 \x01(\x02\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_CENTERROTATEDBOX']._serialized_start=66
  _globals['_CENTERROTATEDBOX']._serialized_end=218
  _globals['_GEOMETRY']._serialized_start=220
  _globals['_GEOMETRY']._serialized_end=345
  _globals['_ZOOMEDCROP']._serialized_start=347
  _globals['_ZOOMEDCROP']._serialized_end=456
# @@protoc_insertion_point(module_scope)
