# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_client_platform.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"lens_overlay_client_platform.proto\x12\x04lens*S\n\x0e\x43lientPlatform\x12\x1f\n\x1b\x43LIENT_PLATFORM_UNSPECIFIED\x10\x00\x12 \n\x1c\x43LIENT_PLATFORM_LENS_OVERLAY\x10\x02\x42\x02H\x03\x62\x06proto3')

_CLIENTPLATFORM = DESCRIPTOR.enum_types_by_name['ClientPlatform']
ClientPlatform = enum_type_wrapper.EnumTypeWrapper(_CLIENTPLATFORM)
CLIENT_PLATFORM_UNSPECIFIED = 0
CLIENT_PLATFORM_LENS_OVERLAY = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _CLIENTPLATFORM._serialized_start=44
  _CLIENTPLATFORM._serialized_end=127
# @@protoc_insertion_point(module_scope)
