# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_text.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_text.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17lens_overlay_text.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\"M\n\x04Text\x12%\n\x0btext_layout\x18\x01 \x01(\x0b\x32\x10.lens.TextLayout\x12\x18\n\x10\x63ontent_language\x18\x02 \x01(\tJ\x04\x08\x03\x10\x04\"\x9a\x05\n\nTextLayout\x12.\n\nparagraphs\x18\x01 \x03(\x0b\x32\x1a.lens.TextLayout.Paragraph\x1a\xc0\x02\n\x04Word\x12&\n\x02id\x18\x01 \x01(\x0b\x32\x1a.lens.TextEntityIdentifier\x12\x12\n\nplain_text\x18\x02 \x01(\t\x12\x1b\n\x0etext_separator\x18\x03 \x01(\tH\x00\x88\x01\x01\x12 \n\x08geometry\x18\x04 \x01(\x0b\x32\x0e.lens.Geometry\x12(\n\x04type\x18\x05 \x01(\x0e\x32\x1a.lens.TextLayout.Word.Type\x12?\n\x10\x66ormula_metadata\x18\x06 \x01(\x0b\x32%.lens.TextLayout.Word.FormulaMetadata\x1a \n\x0f\x46ormulaMetadata\x12\r\n\x05latex\x18\x01 \x01(\t\"\x1d\n\x04Type\x12\x08\n\x04TEXT\x10\x00\x12\x0b\n\x07\x46ORMULA\x10\x01\x42\x11\n\x0f_text_separator\x1aN\n\x04Line\x12$\n\x05words\x18\x01 \x03(\x0b\x32\x15.lens.TextLayout.Word\x12 \n\x08geometry\x18\x02 \x01(\x0b\x32\x0e.lens.Geometry\x1a\xc8\x01\n\tParagraph\x12&\n\x02id\x18\x01 \x01(\x0b\x32\x1a.lens.TextEntityIdentifier\x12$\n\x05lines\x18\x02 \x03(\x0b\x32\x15.lens.TextLayout.Line\x12 \n\x08geometry\x18\x03 \x01(\x0b\x32\x0e.lens.Geometry\x12\x31\n\x11writing_direction\x18\x04 \x01(\x0e\x32\x16.lens.WritingDirection\x12\x18\n\x10\x63ontent_language\x18\x05 \x01(\t\"\"\n\x14TextEntityIdentifier\x12\n\n\x02id\x18\x01 \x01(\x03*\x89\x01\n\x10WritingDirection\x12+\n\'DEFAULT_WRITING_DIRECTION_LEFT_TO_RIGHT\x10\x00\x12#\n\x1fWRITING_DIRECTION_RIGHT_TO_LEFT\x10\x01\x12#\n\x1fWRITING_DIRECTION_TOP_TO_BOTTOM\x10\x02*L\n\tAlignment\x12\x18\n\x14\x44\x45\x46\x41ULT_LEFT_ALIGNED\x10\x00\x12\x11\n\rRIGHT_ALIGNED\x10\x01\x12\x12\n\x0e\x43\x45NTER_ALIGNED\x10\x02\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_text_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_WRITINGDIRECTION']._serialized_start=847
  _globals['_WRITINGDIRECTION']._serialized_end=984
  _globals['_ALIGNMENT']._serialized_start=986
  _globals['_ALIGNMENT']._serialized_end=1062
  _globals['_TEXT']._serialized_start=62
  _globals['_TEXT']._serialized_end=139
  _globals['_TEXTLAYOUT']._serialized_start=142
  _globals['_TEXTLAYOUT']._serialized_end=808
  _globals['_TEXTLAYOUT_WORD']._serialized_start=205
  _globals['_TEXTLAYOUT_WORD']._serialized_end=525
  _globals['_TEXTLAYOUT_WORD_FORMULAMETADATA']._serialized_start=443
  _globals['_TEXTLAYOUT_WORD_FORMULAMETADATA']._serialized_end=475
  _globals['_TEXTLAYOUT_WORD_TYPE']._serialized_start=477
  _globals['_TEXTLAYOUT_WORD_TYPE']._serialized_end=506
  _globals['_TEXTLAYOUT_LINE']._serialized_start=527
  _globals['_TEXTLAYOUT_LINE']._serialized_end=605
  _globals['_TEXTLAYOUT_PARAGRAPH']._serialized_start=608
  _globals['_TEXTLAYOUT_PARAGRAPH']._serialized_end=808
  _globals['_TEXTENTITYIDENTIFIER']._serialized_start=810
  _globals['_TEXTENTITYIDENTIFIER']._serialized_end=844
# @@protoc_insertion_point(module_scope)
