# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_request_id.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_routing_info_pb2 as lens__overlay__routing__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlens_overlay_request_id.proto\x12\x04lens\x1a\x1flens_overlay_routing_info.proto\"\xb7\x01\n\x14LensOverlayRequestId\x12\x0c\n\x04uuid\x18\x01 \x01(\x04\x12\x13\n\x0bsequence_id\x18\x02 \x01(\x05\x12\x19\n\x11image_sequence_id\x18\x03 \x01(\x05\x12\x14\n\x0c\x61nalytics_id\x18\x04 \x01(\x0c\x12\x17\n\x0flong_context_id\x18\t \x01(\x05\x12\x32\n\x0crouting_info\x18\x06 \x01(\x0b\x32\x1c.lens.LensOverlayRoutingInfoB\x02H\x03\x62\x06proto3')



_LENSOVERLAYREQUESTID = DESCRIPTOR.message_types_by_name['LensOverlayRequestId']
LensOverlayRequestId = _reflection.GeneratedProtocolMessageType('LensOverlayRequestId', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYREQUESTID,
  '__module__' : 'lens_overlay_request_id_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayRequestId)
  })
_sym_db.RegisterMessage(LensOverlayRequestId)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYREQUESTID._serialized_start=73
  _LENSOVERLAYREQUESTID._serialized_end=256
# @@protoc_insertion_point(module_scope)
