# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_geometry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_polygon_pb2 as lens__overlay__polygon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blens_overlay_geometry.proto\x12\x04lens\x1a\x1alens_overlay_polygon.proto\"\x98\x01\n\x10\x43\x65nterRotatedBox\x12\x10\n\x08\x63\x65nter_x\x18\x01 \x01(\x02\x12\x10\n\x08\x63\x65nter_y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x12\n\nrotation_z\x18\x05 \x01(\x02\x12-\n\x0f\x63oordinate_type\x18\x06 \x01(\x0e\x32\x14.lens.CoordinateType\"}\n\x08Geometry\x12,\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\x16.lens.CenterRotatedBox\x12+\n\x14segmentation_polygon\x18\x05 \x03(\x0b\x32\r.lens.PolygonJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x06\x10\x07\"m\n\nZoomedCrop\x12$\n\x04\x63rop\x18\x01 \x01(\x0b\x32\x16.lens.CenterRotatedBox\x12\x14\n\x0cparent_width\x18\x02 \x01(\x05\x12\x15\n\rparent_height\x18\x03 \x01(\x05\x12\x0c\n\x04zoom\x18\x04 \x01(\x02\x42\x02H\x03\x62\x06proto3')



_CENTERROTATEDBOX = DESCRIPTOR.message_types_by_name['CenterRotatedBox']
_GEOMETRY = DESCRIPTOR.message_types_by_name['Geometry']
_ZOOMEDCROP = DESCRIPTOR.message_types_by_name['ZoomedCrop']
CenterRotatedBox = _reflection.GeneratedProtocolMessageType('CenterRotatedBox', (_message.Message,), {
  'DESCRIPTOR' : _CENTERROTATEDBOX,
  '__module__' : 'lens_overlay_geometry_pb2'
  # @@protoc_insertion_point(class_scope:lens.CenterRotatedBox)
  })
_sym_db.RegisterMessage(CenterRotatedBox)

Geometry = _reflection.GeneratedProtocolMessageType('Geometry', (_message.Message,), {
  'DESCRIPTOR' : _GEOMETRY,
  '__module__' : 'lens_overlay_geometry_pb2'
  # @@protoc_insertion_point(class_scope:lens.Geometry)
  })
_sym_db.RegisterMessage(Geometry)

ZoomedCrop = _reflection.GeneratedProtocolMessageType('ZoomedCrop', (_message.Message,), {
  'DESCRIPTOR' : _ZOOMEDCROP,
  '__module__' : 'lens_overlay_geometry_pb2'
  # @@protoc_insertion_point(class_scope:lens.ZoomedCrop)
  })
_sym_db.RegisterMessage(ZoomedCrop)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _CENTERROTATEDBOX._serialized_start=66
  _CENTERROTATEDBOX._serialized_end=218
  _GEOMETRY._serialized_start=220
  _GEOMETRY._serialized_end=345
  _ZOOMEDCROP._serialized_start=347
  _ZOOMEDCROP._serialized_end=456
# @@protoc_insertion_point(module_scope)
