# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_text.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17lens_overlay_text.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\"M\n\x04Text\x12%\n\x0btext_layout\x18\x01 \x01(\x0b\x32\x10.lens.TextLayout\x12\x18\n\x10\x63ontent_language\x18\x02 \x01(\tJ\x04\x08\x03\x10\x04\"\x9a\x05\n\nTextLayout\x12.\n\nparagraphs\x18\x01 \x03(\x0b\x32\x1a.lens.TextLayout.Paragraph\x1a\xc0\x02\n\x04Word\x12&\n\x02id\x18\x01 \x01(\x0b\x32\x1a.lens.TextEntityIdentifier\x12\x12\n\nplain_text\x18\x02 \x01(\t\x12\x1b\n\x0etext_separator\x18\x03 \x01(\tH\x00\x88\x01\x01\x12 \n\x08geometry\x18\x04 \x01(\x0b\x32\x0e.lens.Geometry\x12(\n\x04type\x18\x05 \x01(\x0e\x32\x1a.lens.TextLayout.Word.Type\x12?\n\x10\x66ormula_metadata\x18\x06 \x01(\x0b\x32%.lens.TextLayout.Word.FormulaMetadata\x1a \n\x0f\x46ormulaMetadata\x12\r\n\x05latex\x18\x01 \x01(\t\"\x1d\n\x04Type\x12\x08\n\x04TEXT\x10\x00\x12\x0b\n\x07\x46ORMULA\x10\x01\x42\x11\n\x0f_text_separator\x1aN\n\x04Line\x12$\n\x05words\x18\x01 \x03(\x0b\x32\x15.lens.TextLayout.Word\x12 \n\x08geometry\x18\x02 \x01(\x0b\x32\x0e.lens.Geometry\x1a\xc8\x01\n\tParagraph\x12&\n\x02id\x18\x01 \x01(\x0b\x32\x1a.lens.TextEntityIdentifier\x12$\n\x05lines\x18\x02 \x03(\x0b\x32\x15.lens.TextLayout.Line\x12 \n\x08geometry\x18\x03 \x01(\x0b\x32\x0e.lens.Geometry\x12\x31\n\x11writing_direction\x18\x04 \x01(\x0e\x32\x16.lens.WritingDirection\x12\x18\n\x10\x63ontent_language\x18\x05 \x01(\t\"\"\n\x14TextEntityIdentifier\x12\n\n\x02id\x18\x01 \x01(\x03*\x89\x01\n\x10WritingDirection\x12+\n\'DEFAULT_WRITING_DIRECTION_LEFT_TO_RIGHT\x10\x00\x12#\n\x1fWRITING_DIRECTION_RIGHT_TO_LEFT\x10\x01\x12#\n\x1fWRITING_DIRECTION_TOP_TO_BOTTOM\x10\x02*L\n\tAlignment\x12\x18\n\x14\x44\x45\x46\x41ULT_LEFT_ALIGNED\x10\x00\x12\x11\n\rRIGHT_ALIGNED\x10\x01\x12\x12\n\x0e\x43\x45NTER_ALIGNED\x10\x02\x42\x02H\x03\x62\x06proto3')

_WRITINGDIRECTION = DESCRIPTOR.enum_types_by_name['WritingDirection']
WritingDirection = enum_type_wrapper.EnumTypeWrapper(_WRITINGDIRECTION)
_ALIGNMENT = DESCRIPTOR.enum_types_by_name['Alignment']
Alignment = enum_type_wrapper.EnumTypeWrapper(_ALIGNMENT)
DEFAULT_WRITING_DIRECTION_LEFT_TO_RIGHT = 0
WRITING_DIRECTION_RIGHT_TO_LEFT = 1
WRITING_DIRECTION_TOP_TO_BOTTOM = 2
DEFAULT_LEFT_ALIGNED = 0
RIGHT_ALIGNED = 1
CENTER_ALIGNED = 2


_TEXT = DESCRIPTOR.message_types_by_name['Text']
_TEXTLAYOUT = DESCRIPTOR.message_types_by_name['TextLayout']
_TEXTLAYOUT_WORD = _TEXTLAYOUT.nested_types_by_name['Word']
_TEXTLAYOUT_WORD_FORMULAMETADATA = _TEXTLAYOUT_WORD.nested_types_by_name['FormulaMetadata']
_TEXTLAYOUT_LINE = _TEXTLAYOUT.nested_types_by_name['Line']
_TEXTLAYOUT_PARAGRAPH = _TEXTLAYOUT.nested_types_by_name['Paragraph']
_TEXTENTITYIDENTIFIER = DESCRIPTOR.message_types_by_name['TextEntityIdentifier']
_TEXTLAYOUT_WORD_TYPE = _TEXTLAYOUT_WORD.enum_types_by_name['Type']
Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'lens_overlay_text_pb2'
  # @@protoc_insertion_point(class_scope:lens.Text)
  })
_sym_db.RegisterMessage(Text)

TextLayout = _reflection.GeneratedProtocolMessageType('TextLayout', (_message.Message,), {

  'Word' : _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), {

    'FormulaMetadata' : _reflection.GeneratedProtocolMessageType('FormulaMetadata', (_message.Message,), {
      'DESCRIPTOR' : _TEXTLAYOUT_WORD_FORMULAMETADATA,
      '__module__' : 'lens_overlay_text_pb2'
      # @@protoc_insertion_point(class_scope:lens.TextLayout.Word.FormulaMetadata)
      })
    ,
    'DESCRIPTOR' : _TEXTLAYOUT_WORD,
    '__module__' : 'lens_overlay_text_pb2'
    # @@protoc_insertion_point(class_scope:lens.TextLayout.Word)
    })
  ,

  'Line' : _reflection.GeneratedProtocolMessageType('Line', (_message.Message,), {
    'DESCRIPTOR' : _TEXTLAYOUT_LINE,
    '__module__' : 'lens_overlay_text_pb2'
    # @@protoc_insertion_point(class_scope:lens.TextLayout.Line)
    })
  ,

  'Paragraph' : _reflection.GeneratedProtocolMessageType('Paragraph', (_message.Message,), {
    'DESCRIPTOR' : _TEXTLAYOUT_PARAGRAPH,
    '__module__' : 'lens_overlay_text_pb2'
    # @@protoc_insertion_point(class_scope:lens.TextLayout.Paragraph)
    })
  ,
  'DESCRIPTOR' : _TEXTLAYOUT,
  '__module__' : 'lens_overlay_text_pb2'
  # @@protoc_insertion_point(class_scope:lens.TextLayout)
  })
_sym_db.RegisterMessage(TextLayout)
_sym_db.RegisterMessage(TextLayout.Word)
_sym_db.RegisterMessage(TextLayout.Word.FormulaMetadata)
_sym_db.RegisterMessage(TextLayout.Line)
_sym_db.RegisterMessage(TextLayout.Paragraph)

TextEntityIdentifier = _reflection.GeneratedProtocolMessageType('TextEntityIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _TEXTENTITYIDENTIFIER,
  '__module__' : 'lens_overlay_text_pb2'
  # @@protoc_insertion_point(class_scope:lens.TextEntityIdentifier)
  })
_sym_db.RegisterMessage(TextEntityIdentifier)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _WRITINGDIRECTION._serialized_start=847
  _WRITINGDIRECTION._serialized_end=984
  _ALIGNMENT._serialized_start=986
  _ALIGNMENT._serialized_end=1062
  _TEXT._serialized_start=62
  _TEXT._serialized_end=139
  _TEXTLAYOUT._serialized_start=142
  _TEXTLAYOUT._serialized_end=808
  _TEXTLAYOUT_WORD._serialized_start=205
  _TEXTLAYOUT_WORD._serialized_end=525
  _TEXTLAYOUT_WORD_FORMULAMETADATA._serialized_start=443
  _TEXTLAYOUT_WORD_FORMULAMETADATA._serialized_end=475
  _TEXTLAYOUT_WORD_TYPE._serialized_start=477
  _TEXTLAYOUT_WORD_TYPE._serialized_end=506
  _TEXTLAYOUT_LINE._serialized_start=527
  _TEXTLAYOUT_LINE._serialized_end=605
  _TEXTLAYOUT_PARAGRAPH._serialized_start=608
  _TEXTLAYOUT_PARAGRAPH._serialized_end=808
  _TEXTENTITYIDENTIFIER._serialized_start=810
  _TEXTENTITYIDENTIFIER._serialized_end=844
# @@protoc_insertion_point(module_scope)
