# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_text_query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlens_overlay_text_query.proto\x12\x04lens\".\n\tTextQuery\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nis_primary\x18\x02 \x01(\x08\x42\x02H\x03\x62\x06proto3')



_TEXTQUERY = DESCRIPTOR.message_types_by_name['TextQuery']
TextQuery = _reflection.GeneratedProtocolMessageType('TextQuery', (_message.Message,), {
  'DESCRIPTOR' : _TEXTQUERY,
  '__module__' : 'lens_overlay_text_query_pb2'
  # @@protoc_insertion_point(class_scope:lens.TextQuery)
  })
_sym_db.RegisterMessage(TextQuery)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _TEXTQUERY._serialized_start=39
  _TEXTQUERY._serialized_end=85
# @@protoc_insertion_point(module_scope)
