# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_translate_stickiness_signals.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/lens_overlay_translate_stickiness_signals.proto\x12\x04lens\"H\n\x1aTranslateStickinessSignals\x12*\n\"translate_suppress_echo_for_sticky\x18\x01 \x01(\x08\x42\x02H\x03\x62\x06proto3')



_TRANSLATESTICKINESSSIGNALS = DESCRIPTOR.message_types_by_name['TranslateStickinessSignals']
TranslateStickinessSignals = _reflection.GeneratedProtocolMessageType('TranslateStickinessSignals', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATESTICKINESSSIGNALS,
  '__module__' : 'lens_overlay_translate_stickiness_signals_pb2'
  # @@protoc_insertion_point(class_scope:lens.TranslateStickinessSignals)
  })
_sym_db.RegisterMessage(TranslateStickinessSignals)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _TRANSLATESTICKINESSSIGNALS._serialized_start=57
  _TRANSLATESTICKINESSSIGNALS._serialized_end=129
# @@protoc_insertion_point(module_scope)
