# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_selection_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!lens_overlay_selection_type.proto\x12\x04lens*\xdd\x02\n\x18LensOverlaySelectionType\x12\x1a\n\x16UNKNOWN_SELECTION_TYPE\x10\x00\x12\x10\n\x0cTAP_ON_EMPTY\x10\x01\x12\x19\n\x15SELECT_TEXT_HIGHLIGHT\x10\x03\x12\x11\n\rREGION_SEARCH\x10\x07\x12\x12\n\x0eINJECTED_IMAGE\x10\n\x12\x17\n\x13TAP_ON_REGION_GLEAM\x10\x0f\x12\x15\n\x11MULTIMODAL_SEARCH\x10\x12\x12\x1a\n\x16SELECT_TRANSLATED_TEXT\x10\x15\x12\x11\n\rTAP_ON_OBJECT\x10\x16\x12 \n\x1cMULTIMODAL_SUGGEST_TYPEAHEAD\x10\x19\x12\"\n\x1eMULTIMODAL_SUGGEST_ZERO_PREFIX\x10\x1a\x12\x12\n\x0eTRANSLATE_CHIP\x10\x34\x12\x18\n\x14SYMBOLIC_MATH_OBJECT\x10\x35\x42\x02H\x03\x62\x06proto3')

_LENSOVERLAYSELECTIONTYPE = DESCRIPTOR.enum_types_by_name['LensOverlaySelectionType']
LensOverlaySelectionType = enum_type_wrapper.EnumTypeWrapper(_LENSOVERLAYSELECTIONTYPE)
UNKNOWN_SELECTION_TYPE = 0
TAP_ON_EMPTY = 1
SELECT_TEXT_HIGHLIGHT = 3
REGION_SEARCH = 7
INJECTED_IMAGE = 10
TAP_ON_REGION_GLEAM = 15
MULTIMODAL_SEARCH = 18
SELECT_TRANSLATED_TEXT = 21
TAP_ON_OBJECT = 22
MULTIMODAL_SUGGEST_TYPEAHEAD = 25
MULTIMODAL_SUGGEST_ZERO_PREFIX = 26
TRANSLATE_CHIP = 52
SYMBOLIC_MATH_OBJECT = 53


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYSELECTIONTYPE._serialized_start=44
  _LENSOVERLAYSELECTIONTYPE._serialized_end=393
# @@protoc_insertion_point(module_scope)
