# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_platform.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blens_overlay_platform.proto\x12\x04lens*Q\n\x08Platform\x12\x18\n\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x10\n\x0cPLATFORM_WEB\x10\x03\x12\x19\n\x15PLATFORM_LENS_OVERLAY\x10\x06\x42\x02H\x03\x62\x06proto3')

_PLATFORM = DESCRIPTOR.enum_types_by_name['Platform']
Platform = enum_type_wrapper.EnumTypeWrapper(_PLATFORM)
PLATFORM_UNSPECIFIED = 0
PLATFORM_WEB = 3
PLATFORM_LENS_OVERLAY = 6


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _PLATFORM._serialized_start=37
  _PLATFORM._serialized_end=118
# @@protoc_insertion_point(module_scope)
