# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_video_params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_video_context_input_params_pb2 as lens__overlay__video__context__input__params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1flens_overlay_video_params.proto\x12\x04lens\x1a-lens_overlay_video_context_input_params.proto\"f\n\x16LensOverlayVideoParams\x12L\n\x1avideo_context_input_params\x18\x01 \x01(\x0b\x32(.lens.LensOverlayVideoContextInputParamsB\x02H\x03\x62\x06proto3')



_LENSOVERLAYVIDEOPARAMS = DESCRIPTOR.message_types_by_name['LensOverlayVideoParams']
LensOverlayVideoParams = _reflection.GeneratedProtocolMessageType('LensOverlayVideoParams', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYVIDEOPARAMS,
  '__module__' : 'lens_overlay_video_params_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayVideoParams)
  })
_sym_db.RegisterMessage(LensOverlayVideoParams)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYVIDEOPARAMS._serialized_start=88
  _LENSOVERLAYVIDEOPARAMS._serialized_end=190
# @@protoc_insertion_point(module_scope)
