# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_phase_latencies_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+lens_overlay_phase_latencies_metadata.proto\x12\x04lens\"\xd2\x04\n!LensOverlayPhaseLatenciesMetadata\x12<\n\x05phase\x18\x01 \x03(\x0b\x32-.lens.LensOverlayPhaseLatenciesMetadata.Phase\x1a\xb7\x03\n\x05Phase\x12`\n\x14image_downscale_data\x18\x03 \x01(\x0b\x32@.lens.LensOverlayPhaseLatenciesMetadata.Phase.ImageDownscaleDataH\x00\x12Z\n\x11image_encode_data\x18\x04 \x01(\x0b\x32=.lens.LensOverlayPhaseLatenciesMetadata.Phase.ImageEncodeDataH\x00\x1aP\n\x12ImageDownscaleData\x12\x1b\n\x13original_image_size\x18\x01 \x01(\x03\x12\x1d\n\x15\x64ownscaled_image_size\x18\x02 \x01(\x03\x1a\x83\x01\n\x0fImageEncodeData\x12N\n\x13original_image_type\x18\x01 \x01(\x0e\x32\x31.lens.LensOverlayPhaseLatenciesMetadata.ImageType\x12 \n\x18\x65ncoded_image_size_bytes\x18\x02 \x01(\x03\x42\x0c\n\nphase_dataJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03\"5\n\tImageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04JPEG\x10\x01\x12\x07\n\x03PNG\x10\x02\x12\x08\n\x04WEBP\x10\x03\x42\x02H\x03\x62\x06proto3')



_LENSOVERLAYPHASELATENCIESMETADATA = DESCRIPTOR.message_types_by_name['LensOverlayPhaseLatenciesMetadata']
_LENSOVERLAYPHASELATENCIESMETADATA_PHASE = _LENSOVERLAYPHASELATENCIESMETADATA.nested_types_by_name['Phase']
_LENSOVERLAYPHASELATENCIESMETADATA_PHASE_IMAGEDOWNSCALEDATA = _LENSOVERLAYPHASELATENCIESMETADATA_PHASE.nested_types_by_name['ImageDownscaleData']
_LENSOVERLAYPHASELATENCIESMETADATA_PHASE_IMAGEENCODEDATA = _LENSOVERLAYPHASELATENCIESMETADATA_PHASE.nested_types_by_name['ImageEncodeData']
_LENSOVERLAYPHASELATENCIESMETADATA_IMAGETYPE = _LENSOVERLAYPHASELATENCIESMETADATA.enum_types_by_name['ImageType']
LensOverlayPhaseLatenciesMetadata = _reflection.GeneratedProtocolMessageType('LensOverlayPhaseLatenciesMetadata', (_message.Message,), {

  'Phase' : _reflection.GeneratedProtocolMessageType('Phase', (_message.Message,), {

    'ImageDownscaleData' : _reflection.GeneratedProtocolMessageType('ImageDownscaleData', (_message.Message,), {
      'DESCRIPTOR' : _LENSOVERLAYPHASELATENCIESMETADATA_PHASE_IMAGEDOWNSCALEDATA,
      '__module__' : 'lens_overlay_phase_latencies_metadata_pb2'
      # @@protoc_insertion_point(class_scope:lens.LensOverlayPhaseLatenciesMetadata.Phase.ImageDownscaleData)
      })
    ,

    'ImageEncodeData' : _reflection.GeneratedProtocolMessageType('ImageEncodeData', (_message.Message,), {
      'DESCRIPTOR' : _LENSOVERLAYPHASELATENCIESMETADATA_PHASE_IMAGEENCODEDATA,
      '__module__' : 'lens_overlay_phase_latencies_metadata_pb2'
      # @@protoc_insertion_point(class_scope:lens.LensOverlayPhaseLatenciesMetadata.Phase.ImageEncodeData)
      })
    ,
    'DESCRIPTOR' : _LENSOVERLAYPHASELATENCIESMETADATA_PHASE,
    '__module__' : 'lens_overlay_phase_latencies_metadata_pb2'
    # @@protoc_insertion_point(class_scope:lens.LensOverlayPhaseLatenciesMetadata.Phase)
    })
  ,
  'DESCRIPTOR' : _LENSOVERLAYPHASELATENCIESMETADATA,
  '__module__' : 'lens_overlay_phase_latencies_metadata_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayPhaseLatenciesMetadata)
  })
_sym_db.RegisterMessage(LensOverlayPhaseLatenciesMetadata)
_sym_db.RegisterMessage(LensOverlayPhaseLatenciesMetadata.Phase)
_sym_db.RegisterMessage(LensOverlayPhaseLatenciesMetadata.Phase.ImageDownscaleData)
_sym_db.RegisterMessage(LensOverlayPhaseLatenciesMetadata.Phase.ImageEncodeData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYPHASELATENCIESMETADATA._serialized_start=54
  _LENSOVERLAYPHASELATENCIESMETADATA._serialized_end=648
  _LENSOVERLAYPHASELATENCIESMETADATA_PHASE._serialized_start=154
  _LENSOVERLAYPHASELATENCIESMETADATA_PHASE._serialized_end=593
  _LENSOVERLAYPHASELATENCIESMETADATA_PHASE_IMAGEDOWNSCALEDATA._serialized_start=353
  _LENSOVERLAYPHASELATENCIESMETADATA_PHASE_IMAGEDOWNSCALEDATA._serialized_end=433
  _LENSOVERLAYPHASELATENCIESMETADATA_PHASE_IMAGEENCODEDATA._serialized_start=436
  _LENSOVERLAYPHASELATENCIESMETADATA_PHASE_IMAGEENCODEDATA._serialized_end=567
  _LENSOVERLAYPHASELATENCIESMETADATA_IMAGETYPE._serialized_start=595
  _LENSOVERLAYPHASELATENCIESMETADATA_IMAGETYPE._serialized_end=648
# @@protoc_insertion_point(module_scope)
