# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_visual_search_interaction_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2
import owocr.py_lens.lens_overlay_interaction_request_metadata_pb2 as lens__overlay__interaction__request__metadata__pb2
import owocr.py_lens.lens_overlay_visual_search_interaction_log_data_pb2 as lens__overlay__visual__search__interaction__log__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1lens_overlay_visual_search_interaction_data.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\x1a/lens_overlay_interaction_request_metadata.proto\x1a\x35lens_overlay_visual_search_interaction_log_data.proto\"\x83\x02\n&LensOverlayVisualSearchInteractionData\x12J\n\x10interaction_type\x18\x01 \x01(\x0e\x32\x30.lens.LensOverlayInteractionRequestMetadata.Type\x12%\n\x0bzoomed_crop\x18\x07 \x01(\x0b\x32\x10.lens.ZoomedCrop\x12\x11\n\tobject_id\x18\x03 \x01(\t\x12\x41\n\x08log_data\x18\x05 \x01(\x0b\x32/.lens.LensOverlayVisualSearchInteractionLogDataJ\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x05J\x04\x08\x06\x10\x07\x42\x02H\x03\x62\x06proto3')



_LENSOVERLAYVISUALSEARCHINTERACTIONDATA = DESCRIPTOR.message_types_by_name['LensOverlayVisualSearchInteractionData']
LensOverlayVisualSearchInteractionData = _reflection.GeneratedProtocolMessageType('LensOverlayVisualSearchInteractionData', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYVISUALSEARCHINTERACTIONDATA,
  '__module__' : 'lens_overlay_visual_search_interaction_data_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayVisualSearchInteractionData)
  })
_sym_db.RegisterMessage(LensOverlayVisualSearchInteractionData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYVISUALSEARCHINTERACTIONDATA._serialized_start=193
  _LENSOVERLAYVISUALSEARCHINTERACTIONDATA._serialized_end=452
# @@protoc_insertion_point(module_scope)
