# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_knowledge_query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_knowledge_intent_query_pb2 as lens__overlay__knowledge__intent__query__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"lens_overlay_knowledge_query.proto\x12\x04lens\x1a)lens_overlay_knowledge_intent_query.proto\"4\n\x05Query\x12+\n\x0cintent_query\x18\xc2\x95\xe9\x1a \x01(\x0b\x32\x12.lens.FunctionCallB\x02H\x03\x62\x06proto3')



_QUERY = DESCRIPTOR.message_types_by_name['Query']
Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'lens_overlay_knowledge_query_pb2'
  # @@protoc_insertion_point(class_scope:lens.Query)
  })
_sym_db.RegisterMessage(Query)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _QUERY._serialized_start=87
  _QUERY._serialized_end=139
# @@protoc_insertion_point(module_scope)
