# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_surface.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alens_overlay_surface.proto\x12\x04lens*R\n\x07Surface\x12\x17\n\x13SURFACE_UNSPECIFIED\x10\x00\x12\x14\n\x10SURFACE_CHROMIUM\x10\x04\x12\x18\n\x14SURFACE_LENS_OVERLAY\x10*B\x02H\x03\x62\x06proto3')

_SURFACE = DESCRIPTOR.enum_types_by_name['Surface']
Surface = enum_type_wrapper.EnumTypeWrapper(_SURFACE)
SURFACE_UNSPECIFIED = 0
SURFACE_CHROMIUM = 4
SURFACE_LENS_OVERLAY = 42


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _SURFACE._serialized_start=36
  _SURFACE._serialized_end=118
# @@protoc_insertion_point(module_scope)
