# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_cluster_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_routing_info_pb2 as lens__overlay__routing__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1flens_overlay_cluster_info.proto\x12\x04lens\x1a\x1flens_overlay_routing_info.proto\"\x82\x01\n\x16LensOverlayClusterInfo\x12\x19\n\x11server_session_id\x18\x01 \x01(\t\x12\x19\n\x11search_session_id\x18\x02 \x01(\t\x12\x32\n\x0crouting_info\x18\x06 \x01(\x0b\x32\x1c.lens.LensOverlayRoutingInfoB\x02H\x03\x62\x06proto3')



_LENSOVERLAYCLUSTERINFO = DESCRIPTOR.message_types_by_name['LensOverlayClusterInfo']
LensOverlayClusterInfo = _reflection.GeneratedProtocolMessageType('LensOverlayClusterInfo', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYCLUSTERINFO,
  '__module__' : 'lens_overlay_cluster_info_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayClusterInfo)
  })
_sym_db.RegisterMessage(LensOverlayClusterInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYCLUSTERINFO._serialized_start=75
  _LENSOVERLAYCLUSTERINFO._serialized_end=205
# @@protoc_insertion_point(module_scope)
