# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_knowledge_intent_query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_translate_stickiness_signals_pb2 as lens__overlay__translate__stickiness__signals__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)lens_overlay_knowledge_intent_query.proto\x12\x04lens\x1a/lens_overlay_translate_stickiness_signals.proto\"j\n\x0c\x46unctionCall\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x08\x61rgument\x18\x02 \x03(\x0b\x32\x0e.lens.Argument\x12*\n\x07signals\x18\x04 \x01(\x0b\x32\x19.lens.FunctionCallSignals\"a\n\x13\x46unctionCallSignals\x12J\n\x1ctranslate_stickiness_signals\x18\xe6\x81\xbd\x94\x01 \x01(\x0b\x32 .lens.TranslateStickinessSignals\"<\n\x08\x41rgument\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.lens.ArgumentValue\"C\n\rArgumentValue\x12)\n\x0csimple_value\x18\x03 \x01(\x0b\x32\x11.lens.SimpleValueH\x00\x42\x07\n\x05value\".\n\x0bSimpleValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x42\x07\n\x05valueB\x02H\x03\x62\x06proto3')



_FUNCTIONCALL = DESCRIPTOR.message_types_by_name['FunctionCall']
_FUNCTIONCALLSIGNALS = DESCRIPTOR.message_types_by_name['FunctionCallSignals']
_ARGUMENT = DESCRIPTOR.message_types_by_name['Argument']
_ARGUMENTVALUE = DESCRIPTOR.message_types_by_name['ArgumentValue']
_SIMPLEVALUE = DESCRIPTOR.message_types_by_name['SimpleValue']
FunctionCall = _reflection.GeneratedProtocolMessageType('FunctionCall', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONCALL,
  '__module__' : 'lens_overlay_knowledge_intent_query_pb2'
  # @@protoc_insertion_point(class_scope:lens.FunctionCall)
  })
_sym_db.RegisterMessage(FunctionCall)

FunctionCallSignals = _reflection.GeneratedProtocolMessageType('FunctionCallSignals', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONCALLSIGNALS,
  '__module__' : 'lens_overlay_knowledge_intent_query_pb2'
  # @@protoc_insertion_point(class_scope:lens.FunctionCallSignals)
  })
_sym_db.RegisterMessage(FunctionCallSignals)

Argument = _reflection.GeneratedProtocolMessageType('Argument', (_message.Message,), {
  'DESCRIPTOR' : _ARGUMENT,
  '__module__' : 'lens_overlay_knowledge_intent_query_pb2'
  # @@protoc_insertion_point(class_scope:lens.Argument)
  })
_sym_db.RegisterMessage(Argument)

ArgumentValue = _reflection.GeneratedProtocolMessageType('ArgumentValue', (_message.Message,), {
  'DESCRIPTOR' : _ARGUMENTVALUE,
  '__module__' : 'lens_overlay_knowledge_intent_query_pb2'
  # @@protoc_insertion_point(class_scope:lens.ArgumentValue)
  })
_sym_db.RegisterMessage(ArgumentValue)

SimpleValue = _reflection.GeneratedProtocolMessageType('SimpleValue', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEVALUE,
  '__module__' : 'lens_overlay_knowledge_intent_query_pb2'
  # @@protoc_insertion_point(class_scope:lens.SimpleValue)
  })
_sym_db.RegisterMessage(SimpleValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _FUNCTIONCALL._serialized_start=100
  _FUNCTIONCALL._serialized_end=206
  _FUNCTIONCALLSIGNALS._serialized_start=208
  _FUNCTIONCALLSIGNALS._serialized_end=305
  _ARGUMENT._serialized_start=307
  _ARGUMENT._serialized_end=367
  _ARGUMENTVALUE._serialized_start=369
  _ARGUMENTVALUE._serialized_end=436
  _SIMPLEVALUE._serialized_start=438
  _SIMPLEVALUE._serialized_end=484
# @@protoc_insertion_point(module_scope)
