# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_routing_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1flens_overlay_routing_info.proto\x12\x04lens\"\\\n\x16LensOverlayRoutingInfo\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x65ll_address\x18\x03 \x01(\t\x12\x14\n\x0c\x62lade_target\x18\x02 \x01(\tB\x02H\x03\x62\x06proto3')



_LENSOVERLAYROUTINGINFO = DESCRIPTOR.message_types_by_name['LensOverlayRoutingInfo']
LensOverlayRoutingInfo = _reflection.GeneratedProtocolMessageType('LensOverlayRoutingInfo', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYROUTINGINFO,
  '__module__' : 'lens_overlay_routing_info_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayRoutingInfo)
  })
_sym_db.RegisterMessage(LensOverlayRoutingInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYROUTINGINFO._serialized_start=41
  _LENSOVERLAYROUTINGINFO._serialized_end=133
# @@protoc_insertion_point(module_scope)
