# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_client_logs_pb2 as lens__overlay__client__logs__pb2
import owocr.py_lens.lens_overlay_routing_info_pb2 as lens__overlay__routing__info__pb2
import owocr.py_lens.lens_overlay_service_deps_pb2 as lens__overlay__service__deps__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19lens_overlay_server.proto\x12\x04lens\x1a\x1elens_overlay_client_logs.proto\x1a\x1flens_overlay_routing_info.proto\x1a\x1flens_overlay_service_deps.proto\"G\n#LensOverlayServerClusterInfoRequest\x12 \n\x18\x65nable_search_session_id\x18\x01 \x01(\x08\"\x90\x01\n$LensOverlayServerClusterInfoResponse\x12\x19\n\x11server_session_id\x18\x01 \x01(\t\x12\x19\n\x11search_session_id\x18\x02 \x01(\t\x12\x32\n\x0crouting_info\x18\x03 \x01(\x0b\x32\x1c.lens.LensOverlayRoutingInfo\"\x88\x01\n\x16LensOverlayServerError\x12:\n\nerror_type\x18\x01 \x01(\x0e\x32&.lens.LensOverlayServerError.ErrorType\"2\n\tErrorType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x13\n\x0fMISSING_REQUEST\x10\x01\"\xc8\x01\n\x18LensOverlayServerRequest\x12\x38\n\x0fobjects_request\x18\x01 \x01(\x0b\x32\x1f.lens.LensOverlayObjectsRequest\x12@\n\x13interaction_request\x18\x02 \x01(\x0b\x32#.lens.LensOverlayInteractionRequest\x12\x30\n\x0b\x63lient_logs\x18\x03 \x01(\x0b\x32\x1b.lens.LensOverlayClientLogs\"\xc8\x01\n\x19LensOverlayServerResponse\x12+\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1c.lens.LensOverlayServerError\x12:\n\x10objects_response\x18\x02 \x01(\x0b\x32 .lens.LensOverlayObjectsResponse\x12\x42\n\x14interaction_response\x18\x03 \x01(\x0b\x32$.lens.LensOverlayInteractionResponseB\x02H\x03\x62\x06proto3')



_LENSOVERLAYSERVERCLUSTERINFOREQUEST = DESCRIPTOR.message_types_by_name['LensOverlayServerClusterInfoRequest']
_LENSOVERLAYSERVERCLUSTERINFORESPONSE = DESCRIPTOR.message_types_by_name['LensOverlayServerClusterInfoResponse']
_LENSOVERLAYSERVERERROR = DESCRIPTOR.message_types_by_name['LensOverlayServerError']
_LENSOVERLAYSERVERREQUEST = DESCRIPTOR.message_types_by_name['LensOverlayServerRequest']
_LENSOVERLAYSERVERRESPONSE = DESCRIPTOR.message_types_by_name['LensOverlayServerResponse']
_LENSOVERLAYSERVERERROR_ERRORTYPE = _LENSOVERLAYSERVERERROR.enum_types_by_name['ErrorType']
LensOverlayServerClusterInfoRequest = _reflection.GeneratedProtocolMessageType('LensOverlayServerClusterInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYSERVERCLUSTERINFOREQUEST,
  '__module__' : 'lens_overlay_server_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayServerClusterInfoRequest)
  })
_sym_db.RegisterMessage(LensOverlayServerClusterInfoRequest)

LensOverlayServerClusterInfoResponse = _reflection.GeneratedProtocolMessageType('LensOverlayServerClusterInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYSERVERCLUSTERINFORESPONSE,
  '__module__' : 'lens_overlay_server_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayServerClusterInfoResponse)
  })
_sym_db.RegisterMessage(LensOverlayServerClusterInfoResponse)

LensOverlayServerError = _reflection.GeneratedProtocolMessageType('LensOverlayServerError', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYSERVERERROR,
  '__module__' : 'lens_overlay_server_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayServerError)
  })
_sym_db.RegisterMessage(LensOverlayServerError)

LensOverlayServerRequest = _reflection.GeneratedProtocolMessageType('LensOverlayServerRequest', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYSERVERREQUEST,
  '__module__' : 'lens_overlay_server_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayServerRequest)
  })
_sym_db.RegisterMessage(LensOverlayServerRequest)

LensOverlayServerResponse = _reflection.GeneratedProtocolMessageType('LensOverlayServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYSERVERRESPONSE,
  '__module__' : 'lens_overlay_server_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayServerResponse)
  })
_sym_db.RegisterMessage(LensOverlayServerResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYSERVERCLUSTERINFOREQUEST._serialized_start=133
  _LENSOVERLAYSERVERCLUSTERINFOREQUEST._serialized_end=204
  _LENSOVERLAYSERVERCLUSTERINFORESPONSE._serialized_start=207
  _LENSOVERLAYSERVERCLUSTERINFORESPONSE._serialized_end=351
  _LENSOVERLAYSERVERERROR._serialized_start=354
  _LENSOVERLAYSERVERERROR._serialized_end=490
  _LENSOVERLAYSERVERERROR_ERRORTYPE._serialized_start=440
  _LENSOVERLAYSERVERERROR_ERRORTYPE._serialized_end=490
  _LENSOVERLAYSERVERREQUEST._serialized_start=493
  _LENSOVERLAYSERVERREQUEST._serialized_end=693
  _LENSOVERLAYSERVERRESPONSE._serialized_start=696
  _LENSOVERLAYSERVERRESPONSE._serialized_end=896
# @@protoc_insertion_point(module_scope)
