# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_visual_search_interaction_log_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_client_platform_pb2 as lens__overlay__client__platform__pb2
import owocr.py_lens.lens_overlay_filters_pb2 as lens__overlay__filters__pb2
import owocr.py_lens.lens_overlay_selection_type_pb2 as lens__overlay__selection__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5lens_overlay_visual_search_interaction_log_data.proto\x12\x04lens\x1a\"lens_overlay_client_platform.proto\x1a\x1alens_overlay_filters.proto\x1a!lens_overlay_selection_type.proto\"\xd0\x01\n)LensOverlayVisualSearchInteractionLogData\x12%\n\x0b\x66ilter_data\x18\x01 \x01(\x0b\x32\x10.lens.FilterData\x12\x34\n\x13user_selection_data\x18\x02 \x01(\x0b\x32\x17.lens.UserSelectionData\x12\x17\n\x0fis_parent_query\x18\x03 \x01(\x08\x12-\n\x0f\x63lient_platform\x18\x04 \x01(\x0e\x32\x14.lens.ClientPlatform\">\n\nFilterData\x12\x30\n\x0b\x66ilter_type\x18\x01 \x01(\x0e\x32\x1b.lens.LensOverlayFilterType\"K\n\x11UserSelectionData\x12\x36\n\x0eselection_type\x18\x01 \x01(\x0e\x32\x1e.lens.LensOverlaySelectionTypeB\x02H\x03\x62\x06proto3')



_LENSOVERLAYVISUALSEARCHINTERACTIONLOGDATA = DESCRIPTOR.message_types_by_name['LensOverlayVisualSearchInteractionLogData']
_FILTERDATA = DESCRIPTOR.message_types_by_name['FilterData']
_USERSELECTIONDATA = DESCRIPTOR.message_types_by_name['UserSelectionData']
LensOverlayVisualSearchInteractionLogData = _reflection.GeneratedProtocolMessageType('LensOverlayVisualSearchInteractionLogData', (_message.Message,), {
  'DESCRIPTOR' : _LENSOVERLAYVISUALSEARCHINTERACTIONLOGDATA,
  '__module__' : 'lens_overlay_visual_search_interaction_log_data_pb2'
  # @@protoc_insertion_point(class_scope:lens.LensOverlayVisualSearchInteractionLogData)
  })
_sym_db.RegisterMessage(LensOverlayVisualSearchInteractionLogData)

FilterData = _reflection.GeneratedProtocolMessageType('FilterData', (_message.Message,), {
  'DESCRIPTOR' : _FILTERDATA,
  '__module__' : 'lens_overlay_visual_search_interaction_log_data_pb2'
  # @@protoc_insertion_point(class_scope:lens.FilterData)
  })
_sym_db.RegisterMessage(FilterData)

UserSelectionData = _reflection.GeneratedProtocolMessageType('UserSelectionData', (_message.Message,), {
  'DESCRIPTOR' : _USERSELECTIONDATA,
  '__module__' : 'lens_overlay_visual_search_interaction_log_data_pb2'
  # @@protoc_insertion_point(class_scope:lens.UserSelectionData)
  })
_sym_db.RegisterMessage(UserSelectionData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LENSOVERLAYVISUALSEARCHINTERACTIONLOGDATA._serialized_start=163
  _LENSOVERLAYVISUALSEARCHINTERACTIONLOGDATA._serialized_end=371
  _FILTERDATA._serialized_start=373
  _FILTERDATA._serialized_end=435
  _USERSELECTIONDATA._serialized_start=437
  _USERSELECTIONDATA._serialized_end=512
# @@protoc_insertion_point(module_scope)
