# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_payload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alens_overlay_payload.proto\x12\x04lens\"0\n\x0b\x43lientImage\x12\x15\n\rimage_content\x18\x01 \x01(\x0cJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04\x42\x02H\x03\x62\x06proto3')



_CLIENTIMAGE = DESCRIPTOR.message_types_by_name['ClientImage']
ClientImage = _reflection.GeneratedProtocolMessageType('ClientImage', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTIMAGE,
  '__module__' : 'lens_overlay_payload_pb2'
  # @@protoc_insertion_point(class_scope:lens.ClientImage)
  })
_sym_db.RegisterMessage(ClientImage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _CLIENTIMAGE._serialized_start=36
  _CLIENTIMAGE._serialized_end=84
# @@protoc_insertion_point(module_scope)
