# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_image_data.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_image_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlens_overlay_image_data.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\"\x90\x01\n\tImageData\x12#\n\x07payload\x18\x01 \x01(\x0b\x32\x12.lens.ImagePayload\x12+\n\x0eimage_metadata\x18\x03 \x01(\x0b\x32\x13.lens.ImageMetadata\x12+\n\x13significant_regions\x18\x04 \x03(\x0b\x32\x0e.lens.GeometryJ\x04\x08\x02\x10\x03\")\n\x0cImagePayload\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0cJ\x04\x08\x02\x10\x03\"4\n\rImageMetadata\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05J\x04\x08\x06\x10\x07\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_image_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_IMAGEDATA']._serialized_start=69
  _globals['_IMAGEDATA']._serialized_end=213
  _globals['_IMAGEPAYLOAD']._serialized_start=215
  _globals['_IMAGEPAYLOAD']._serialized_end=256
  _globals['_IMAGEMETADATA']._serialized_start=258
  _globals['_IMAGEMETADATA']._serialized_end=310
# @@protoc_insertion_point(module_scope)
