# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_client_logs.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_client_logs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_phase_latencies_metadata_pb2 as lens__overlay__phase__latencies__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1elens_overlay_client_logs.proto\x12\x04lens\x1a+lens_overlay_phase_latencies_metadata.proto\"\xa4\x04\n\x15LensOverlayClientLogs\x12I\n\x18phase_latencies_metadata\x18\x01 \x01(\x0b\x32\'.lens.LensOverlayPhaseLatenciesMetadata\x12S\n\x18lens_overlay_entry_point\x18\x02 \x01(\x0e\x32\x31.lens.LensOverlayClientLogs.LensOverlayEntryPoint\x12\x11\n\tpaella_id\x18\x03 \x01(\x04\x12#\n\x1bmetrics_collection_disabled\x18\x05 \x01(\x08\"\xac\x02\n\x15LensOverlayEntryPoint\x12\x17\n\x13UNKNOWN_ENTRY_POINT\x10\x00\x12\x0c\n\x08\x41PP_MENU\x10\x01\x12\x15\n\x11PAGE_CONTEXT_MENU\x10\x02\x12\x16\n\x12IMAGE_CONTEXT_MENU\x10\x03\x12\x12\n\x0eOMNIBOX_BUTTON\x10\x04\x12\x12\n\x0eTOOLBAR_BUTTON\x10\x05\x12\x10\n\x0c\x46IND_IN_PAGE\x10\x06\x12\x17\n\x13OMNIBOX_PAGE_ACTION\x10\x07\x12!\n\x1dOMNIBOX_CONTEXTUAL_SUGGESTION\x10\x08\x12\x18\n\x14HOMEWORK_ACTION_CHIP\x10\t\x12\x15\n\x11TEXT_CONTEXT_MENU\x10\n\x12\x16\n\x12VIDEO_CONTEXT_MENU\x10\x0bJ\x04\x08\x04\x10\x05\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_client_logs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LENSOVERLAYCLIENTLOGS']._serialized_start=86
  _globals['_LENSOVERLAYCLIENTLOGS']._serialized_end=634
  _globals['_LENSOVERLAYCLIENTLOGS_LENSOVERLAYENTRYPOINT']._serialized_start=328
  _globals['_LENSOVERLAYCLIENTLOGS_LENSOVERLAYENTRYPOINT']._serialized_end=628
# @@protoc_insertion_point(module_scope)
