# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_cluster_info.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'lens_overlay_cluster_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import owocr.py_lens.lens_overlay_routing_info_pb2 as lens__overlay__routing__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1flens_overlay_cluster_info.proto\x12\x04lens\x1a\x1flens_overlay_routing_info.proto\"\x82\x01\n\x16LensOverlayClusterInfo\x12\x19\n\x11server_session_id\x18\x01 \x01(\t\x12\x19\n\x11search_session_id\x18\x02 \x01(\t\x12\x32\n\x0crouting_info\x18\x06 \x01(\x0b\x32\x1c.lens.LensOverlayRoutingInfoB\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_cluster_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LENSOVERLAYCLUSTERINFO']._serialized_start=75
  _globals['_LENSOVERLAYCLUSTERINFO']._serialized_end=205
# @@protoc_insertion_point(module_scope)
